ui: mocha-tdd
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: 5.1..latest
  - name: opera
    version: [12, latest]
  - name: safari
    version: 6..latest
